### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-permalink-service#13]
can you just update the docs with the new `expires` field here: https://github.com/qwc-services/qwc-permalink-service#environment-variables?

```
CREATE TABLE permalinks
(
  key character(10) NOT NULL PRIMARY KEY,
  data text,
  date date,
  expires date
);

```

Thanks!

**Comment by manisandro** [comment]
Thanks, done in https://github.com/qwc-services/qwc-permalink-service/commit/eadb419006cb12f4407726e6624128084031e8bd
